# Generated by Django 4.2 on 2025-09-28 18:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cliente', models.CharField(max_length=100)),
                ('veiculo', models.CharField(blank=True, max_length=100)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ANDAMENTO', 'Em Andamento'), ('IMPEDIDO', 'Impedido'), ('ARQUIVADO', 'Arquivado'), ('CONCLUIDO', 'Concluído')], default='PENDENTE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
